services:
  - type: web
    name: n8n
    env: docker
    plan: free
   
    envVars:
      - key: N8N_HOST
        value: n8n-ocse.onrender.com
      - key: N8N_PORT
        value: 10000
      - key: N8N_LISTEN_ADDRESS
        value: 0.0.0.0
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-ocse.onrender.com/
      - key: N8N_EDITOR_BASE_URL
        value: https://n8n-ocse.onrender.com/
      - key: PORT
        value: 10000
